a.out:                                                
	gcc smooth.c -c 
	gcc -c glm.c -lGL -lGLU -lglut
	gcc -c gltb.c -lGL -lGLU -lglut      
	gcc smooth.c glm.o gltb.o -lGL -lGLU -lglut  
                              

